### PR TITLE
CONJ-623: Increase connection logging when Primary node connection fails 

### PR DESCRIPTION
**Pull request by fgaule**
https://jira.mariadb.org/browse/CONJ-623

### CODE REVIEW

**Comment by fgaule** [comment]
@rusher seems like CI is failing in spite of my PR :disappointed:

**Comment by rusher** [comment]
Hi @fgaule,

Thanks for your contribution. For the failed test, that's not due to your change : the reason pull request test doesn't work anymore is due to new travis securoty restriction : https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions. I've just correct master so pull request test will now work. 

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Diego

**Comment by fgaule** [comment]
I hereby declare that this whole PR is under the BSW-new licence.

**Comment by rusher** [comment]
you probably mean  BSD-new licence :)

**Comment by fgaule** [comment]
I hereby declare that this whole PR is under the BSD-new licence. :smile:

**Pull request merged**
