### PR TITLE
Change the query to fetch innodb_read_only from SHOW GLOBAL VARIABLES…

### PR DESCRIPTION
**Pull request by matsuzayaws**
… into SELECT to reduce mutex contention

### CODE REVIEW

**Comment by matsuzayaws** [comment]
```fill_variables()``` in ```sql/show.cc```, the function corresponding to ```SHOW GLOBAL VARIABLES``` command, acquires ```LOCK_plugin_delete``` mutex on Aurora MySQL the same as MySQL.

If there are thousands of clients, the client will execute huge amount of ```SHOW GLOBAL VARIABLES LIKE 'innodb_read_only'``` statements and it will then cause performance impact due to mutex contention.  
Since ```SELECT @@innodb_read_only``` doesn't have any side-effect for performance, it is more preferred than ```SHOW GLOBAL VARIABLES```.

**Comment by rusher** [comment]
Need to confirm that is possible. Using "SHOW" was intentional, because Galera detached node only permit SHOW / SET commands.

**Comment by rusher** [comment]
Forget last comment, it doesn't apply in this case. 

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license. (The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/)

Please indicate in a comment below that you are contributing your new code of the whole pull request under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
diego

**Comment by matsuzayaws** [comment]
Thank you for your comment, Diego. I agree with submitting my code in this PR under the BSD-new license.

**Pull request merged**
