### PR TITLE
CONJ-496

### PR DESCRIPTION
**Pull request by krisiye**

### CODE REVIEW

**Comment by rusher** [comment]
Hi @krisiye ,

Good contribution.

This will be added to next correction version (2.0.3).

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license. (The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/)

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
diego

**Comment by krisiye** [comment]
I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by krisiye** [comment]
@rusher - Do we know if we would also get a 1.6.2  (java 7) released with this update?

**Comment by rusher** [comment]
A java 7 version will be released too (1.6.2)

**Comment by krisiye** [comment]
Also noticed below that appveyor checks and travis-ci (on the max-scale tests) were failing on code thats unrelated to this PR. Is that ok to leave it that way?

**Comment by rusher** [comment]
i've seen that and that will be corrected during merge.

**Comment by krisiye** [comment]
Thanks. Also if you have any ETA for the releases that will be helpful. I could also work with a SNAPSHOT if the releases will take longer.

**Comment by rusher** [comment]
Release will be done tomorrow

**Comment by krisiye** [comment]
@rusher  - thanks for the info. Let me know if you want me to PR against develop or a different branch just in case.

**Comment by krisiye** [comment]
@rusher  - This PR was not merged, and i also see a release done for 1.6.2/2.0.3 which does not include this. Not sure why. any idea?

**Comment by sfahrenholz** [comment]
@krisiye The PR is in the release, see https://github.com/MariaDB/mariadb-connector-j/commit/e34119626b73a58239b718f6f74720e63023640a
He using an other workflow maybe for merging (PR into local branch > quash all to remote branch), but i dont know it really

**Comment by krisiye** [comment]
@sfahrenholz - The PR was merged to develop but that was after the release. JIRA is updated. The new targets are 
2.1.0, 1.6.4. We have a 2.1.0-SNAPSHOT available and i have requested if a 1.6.4-SNAPSHOT be made available as well for testing purposes.

**Comment by krisiye** [comment]
@rusher  - I updated the PR for the comments and opened another https://github.com/MariaDB/mariadb-connector-j/pull/109 against develop since this is already on develop. Let me know if you would like me to close this one out.

**Comment by krisiye** [comment]
Closing since commits from this PR were merged to develop instead.

**Pull request closed without merging**
