### PR TITLE
Fixing ConcurrentModificationException - Incorrect Use of CopyOnWriteArrayList

### PR DESCRIPTION
**Pull request by kaja-mohideen**
Incorrect use of CopyOnWriteArrayList causes ConcurrentModificationException. Fixing it.

### CODE REVIEW

**Comment by rusher** [comment]
Hi kaja-mohideen,

Right, thanks for you contribution !

Similar to other open source projects, the MariaDB Foundation needs to have shared ownership of all code that is included in the MariaDB distribution. The easiest way to achieve this is by submitting your code under the BSD-new license.

The other alternative is to sign the code contribution agreement which can be found here: https://mariadb.com/kb/en/mariadb/mca/

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license or that you have filled out the contribution agreement and sent it.

Thanks,
Diego

**Comment by kaja-mohideen** [comment]
I'll check with my employer on what is the right option and update here.

**Comment by kaja-mohideen** [comment]
Have initiated the process to make this contribution. Have created the ticket https://jira.mariadb.org/browse/CONJ-362 for that purpose.

**Comment by kaja-mohideen** [comment]
Please reject this Pull Request, as it is created from repo forked to my personal account. I'll raise a new PR soon.

**Pull request closed without merging**
