### PR TITLE
[CONJ-245] fix using closed connection error

### PR DESCRIPTION
**Pull request by andyjojo**
if we using client with HAproxy + mariadb galera, then if the network is not very good, the connection is closed, the client will first call PakcetOutputStream.close() and then PacketOutputStream.startPacket but buffer is null, then NullpointerException occurs.

javax.persistence.PersistenceException: java.lang.NullPointerException
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:484)
	at MariaDBTest$2.run(MariaDBTest.java:52)
Caused by: java.lang.NullPointerException
	at org.mariadb.jdbc.internal.stream.PacketOutputStream.startPacket(PacketOutputStream.java:68)
	at org.mariadb.jdbc.internal.stream.PacketOutputStream.startPacket(PacketOutputStream.java:78)
	at org.mariadb.jdbc.internal.packet.send.SendTextQueryPacket.send(SendTextQueryPacket.java:101)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.sendQuery(AbstractQueryProtocol.java:388)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:382)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:339)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:280)
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:448)
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:119)
	at org.eclipse.persistence.internal.databaseaccess.DatabasePlatform.wasFailureCommunicationBased(DatabasePlatform.java:2914)
	at org.eclipse.persistence.platform.server.ServerPlatformBase.wasFailureCommunicationBased(ServerPlatformBase.java:528)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1616)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicBeginTransaction(DatabaseAccessor.java:243)
	at org.eclipse.persistence.internal.databaseaccess.DatasourceAccessor.beginTransaction(DatasourceAccessor.java:255)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicBeginTransaction(AbstractSession.java:732)
	at org.eclipse.persistence.sessions.server.ClientSession.addWriteConnection(ClientSession.java:747)
	at org.eclipse.persistence.sessions.server.ServerSession.acquireClientConnection(ServerSession.java:250)
	at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:277)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:242)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:228)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeSelectCall(DatasourceCallQueryMechanism.java:299)
	at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.selectAllRows(DatasourceCallQueryMechanism.java:694)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRowsFromTable(ExpressionQueryMechanism.java:2740)
	at org.eclipse.persistence.internal.queries.ExpressionQueryMechanism.selectAllRows(ExpressionQueryMechanism.java:2693)
	at org.eclipse.persistence.queries.ReadAllQuery.executeObjectLevelReadQuery(ReadAllQuery.java:541)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeDatabaseQuery(ObjectLevelReadQuery.java:1173)
	at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:904)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.execute(ObjectLevelReadQuery.java:1132)
	at org.eclipse.persistence.queries.ReadAllQuery.execute(ReadAllQuery.java:442)
	at org.eclipse.persistence.queries.ObjectLevelReadQuery.executeInUnitOfWork(ObjectLevelReadQuery.java:1220)
	at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:2896)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1857)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1839)
	at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1804)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:258)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)

### CODE REVIEW

**Comment by jentfoo** [comment]
I wonder if a better option here might not be to set this to `ByteBuffer.allocate(0)`?

In any case, my vote would be not to have commented out code.

**Comment by andyjojo** [comment]
yes
agree with you
Thanks

发自我的 iPhone

在 2016年1月11日，下午11:16，Mike Jensen <notifications@github.com<mailto:notifications@github.com>> 写道：


I wonder if a better option here might not be to set this to ByteBuffer.allocate(0)?

In any case, my vote would be not to have commented out code.

―

**Comment by andyjojo** [comment]
I will have a try tomorrow and will
let you know the result. Thanks

发自我的 iPhone

在 2016年1月11日，下午11:16，Mike Jensen <notifications@github.com<mailto:notifications@github.com>> 写道：


I wonder if a better option here might not be to set this to ByteBuffer.allocate(0)?

In any case, my vote would be not to have commented out code.

―

**Comment by rusher** [comment]
Hi andyjojo, 

Just to be sure of the problem, it seems the problem is due to the use statement after connection close, like : 
```
        Connection connection = DriverManager.getConnection("jdbc:mariadb:/....");
        Statement statement = connection.createStatement();
        try {
            Statement otherStatement = connection.createStatement();
            otherStatement.execute("QUERY"); 
        } catch (SQLException e) {
            //throw connection exception (SQLState "08XXX") due to network instability
            //otherStatement and connection will be closed
            //but method continue
        }
        //Will throw this nullPointerException
        statement.execute("QUERY");
```
Thanks to report that, but the correction seem not to change the PacketOutputStream, since socket is close. The thing is to check "connected" status in the AbstractQueryProtocol, before executing a query and to throw a connection exception since connection is closed. That way, if driver is configured to support failover, a new connection will be created, if not, the statement will be closed and throw exception.  
 I've created a JIRA issue about that : CONJ-245

**Comment by andyjojo** [comment]
OK，Thank you
After you guys fix it, I will try to check it.

Thanks

发自我的 iPhone

在 2016年1月12日，下午4:19，diego dupin <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi andyjojo,

Just to be sure of the problem, it seems the problem is due to the use statement after connection close, like :

        Connection connection = DriverManager.getConnection("jdbc:mariadb:/....");
        Statement statement = connection.createStatement();
        try {
            Statement otherStatement = connection.createStatement();
            otherStatement.execute("QUERY");
        } catch (SQLException e) {
            //throw connection exception (SQLState "08XXX") due to network instability
            //otherStatement and connection will be closed
            //but method continue
        }
        //Will throw this nullPointerException
        statement.execute("QUERY");


Thanks to report that, but the correction seem not to change the PacketOutputStream, since socket is close. The thing is to check "connected" status in the AbstractQueryProtocol, before executing a query and to throw a connection exception since connection is closed. That way, if driver is configured to support failover, a new connection will be created, if not, the statement will be closed and throw exception.

I've created a JIRA issue about that : CONJ-245

―

**Pull request closed without merging**
