### PR TITLE
NPE fix if url used like: jdbc:mariadb://localhost/testj?user=root&maxPoolSize=10

### PR DESCRIPTION
**Pull request by rbhawsar**
//Sample Program to create NullPointerException:

public class ConnectionUsingDS {
    public static void main(String args[]) throws SQLException {
        MariaDbPoolDataSource pool =
                new MariaDbPoolDataSource("jdbc:mariadb://localhost/testj?user=root&maxPoolSize=10");
        try (Connection conn = pool.getConnection()) {
            try(Statement stmt = conn.createStatement()){
                ResultSet rs = stmt.executeQuery("select 'Hello World!'");
                while(rs.next()){
                    System.out.println(rs.getString(1));
                }
               System.out.println(pool.getDatabaseName() +", "+pool.getPort());
            }
        }

    }
}
//Output: 
//Hello World!
//Exception in thread "main" java.lang.NullPointerException
//	at org.mariadb.jdbc.MariaDbPoolDataSource.getPort(MariaDbPoolDataSource.java:153)
//	at mariadb.test.connection.ConnectionUsingDS.main(ConnectionUsingDS.java:32)

### CODE REVIEW

**Comment by rbhawsar** [comment]
after the fix output of program changes to 
Hello World!
testj, 3306

**Comment by rbhawsar** [comment]
I am contributing all code of this whole pull request, including all affected files, under the BSD-new license.

**Comment by rbhawsar** [comment]
travis job is failing with the error: Could not connect to HostAddress{host='null', port=3306, type='slave'}. null.

Can anyone help me on fixing the job and reviewing my PR.

**Comment by rusher** [comment]
Hi @rbhawsar .

Thanks for this pull request. That will be merged in develop branch soon. 

The error is not due to your PR. It seems hidden environment variable from Travis does not apply to PR anymore. I need to check that then and confirm it and changed tests accordingly if it's the case.

Diego

**Comment by rbhawsar** [comment]
Hi @rusher,
thank you, really appreciate it.

Best,
Rahul

**Comment by rusher** [comment]
Right, just for your information, the reason pull request test doesn't work anymore :  https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

I'll merge PR's today ( and correct test so they work even if not having the Travis secure environment variables)

**Comment by rusher** [comment]
merge into develop branch (will be on next correction release)

**Pull request merged**
